import unicodedata

print(unicodedata.lookup('ELEMENT OF'))
print(unicodedata.name('∈'))
print(unicodedata.name('्'))
print(unicodedata.lookup('DEVANAGARI SIGN VIRAMA'))
print(unicodedata.name('र'))
print(unicodedata.lookup('DEVANAGARI LETTER RA'))
print(unicodedata.name('₹'))
print(unicodedata.lookup('INDIAN RUPEE SIGN'))
print()

print(unicodedata.decimal('१'))
print(unicodedata.digit('२'))
print(unicodedata.numeric('५'))
print()

print(unicodedata.category('∈'))
print(unicodedata.category('्'))
print(unicodedata.category('र'))
print(unicodedata.category('₹'))
print(unicodedata.category('१'))
print()

print(unicodedata.bidirectional('∈'))
print(unicodedata.bidirectional('्'))
print(unicodedata.bidirectional('र'))
print(unicodedata.bidirectional('₹'))
print(unicodedata.bidirectional('१'))
print()

print(unicodedata.combining('∈'))
print(unicodedata.combining('्'))
print(unicodedata.combining('र'))
print(unicodedata.combining('₹'))
print(unicodedata.combining('१'))
print()

print(unicodedata.east_asian_width('∈'))
print(unicodedata.east_asian_width('्'))
print(unicodedata.east_asian_width('र'))
print(unicodedata.east_asian_width('₹'))
print(unicodedata.east_asian_width('१'))
print()

print(unicodedata.decomposition('∈'))
print(unicodedata.decomposition('्'))
print(unicodedata.decomposition('र'))
print(unicodedata.decomposition('₹'))
print(unicodedata.decomposition('१'))
print()